FROM php:8.2-fpm

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libzip-dev \
    libxml2-dev \
    libpq-dev \
    && docker-php-ext-install \
    zip \
    intl \
    pdo \
    pdo_pgsql

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www/symfony

# Ustawienie uprawnień
RUN chown -R www-data:www-data /var/www/symfony